Log:
  Level: info

Database:
  Postgres:
    Host: db
    Port: 5432
    Database: zitadel
    User:
      Username: zitadel
      Password: zitadel
    Admin:
      Username: postgres
      Password: postgres
    SSL:
      Mode: disable
